### ISSUE TITLE
Error GET & preventDefault

### ISSUE THREAD

**Issue by Rachiid007** [liorchamla/amu-tp-vanilla-todo#8]
Bonjour, j'ai effectué exactement les mêmes manipulations qu'il y a dans le TP mais j'ai cette erreur :

![image](https://user-images.githubusercontent.com/91373823/161514928-c42b3851-5bb5-4b45-8c30-42d88cb333b4.png)

et lorsque je clique sur le bouton (pour ajouter une tache), la page se rafraichit. Le Prevent Défaut est bien présent !

Merci

**Comment by liorchamla** [comment]
C'est quoi cette histoire de font Roboto Regular ? ôÔ
